### ISSUE TITLE
Supplering af friluftsdata (titler på UK, G)

### ISSUE THREAD

**Issue by hvingel-l** [OpenFKG/fkg-postgresql#100]
I temaerne:
Facilitet_pkt (5800)
Facilitet_flade (5801)
Facilitet_linje (5802)
er der brug for at supplere datamodellen med følgende felter:
- navn_uk
- navn_d

Todo:

 - [x] Modelopdatering
 - [x] Change-script
 - [x] views og triggere
 - [x] doc update

**Comment by cfischer00** [comment]
@hvingel-l : Jeg har opsplittet dit oprindelige issue i 2 dele. Det er lettest for udviklingen og kommunikationen, at vi deler issues i afgrænsede opgaver

**Comment by cfischer00** [comment]
Todo:

 - [ ] Modelopdatering
 - [ ] Change-script
 - [ ] views og triggere
