### ISSUE TITLE
Langt beskrivelsesfelt til tilgængelighedsioplysninger

### ISSUE THREAD

**Issue by hvingel-l** [OpenFKG/fkg-postgresql#116]
I Facilitet_punkt (5800), Facilitet_flade (5801) og Faciltiet_linje (5802) oprettes i forlængelse af eksisterende "kort" og "langt beskrivelsesfelt" til "langt beskrivelsesfelt til tilgængelighedsoplysnigner"

**Comment by cfischer00** [comment]
Jeg læser teksten som at der _alene_ skal oprettes et supplerende felt til beskrivelse af tilgængelighedsoplysninger. Feltet skal være ligeså langt som det eksisterende lang_beskr (3.000 tegn).

Navn på feltet bliver `tilgaeng_beskriv`

**Comment by cfischer00** [comment]
Feltet tilgaeng_beskriv skal indgå i JSON objektet - jeg kan ikke se noget argument for at have det liggende udenfor

**Comment by hvingel-l** [comment]
Der er brug for et fritekst-felt til en "blød" tilgængelighedsbeskrivelse af faciliteten/ruten som supplement til detaljerne i JSON feltet. Ligesom der findes en blød (kort og lang) beskrivelse generelt. Så feltet skal gerne oprettes udenfor JSON objektet

**Comment by cfischer00** [comment]
Ja det er jeg med på, men selve feltet til tilgængelighedsbeskrivelse bør ligge i JSON feltet i modellen.

Så vidt jeg kan se, giver det absolut ingen begrænsninger at lægge det i JSON-feltet.

**Comment by cfischer00** [comment]
@hvingel-l har forklaret årsagen til at feltet skal være udenfor JSON objektet. GIS-folkene har ellers svært ved at håndtere det. Jeg lægger mig fladt ned.
