### ISSUE TITLE
Supplerende felter i billedtabel (3 stk)

### ISSUE THREAD

**Issue by hvingel-l** [OpenFKG/fkg-postgresql#117]
I billedtabel oprettes tre felter til:
1) billedtekst
2) alternativ tekst
3) copyright

**Comment by cfischer00** [comment]
`copyright` eksisterer allerede som felt i `t_7900_foto_t`

**Comment by cfischer00** [comment]
- [ ] billedtekst text(3000) NULL
 - [ ] alt_tekst text(254) NULL
