### ISSUE TITLE
I billedtabel oprettes felt til mærkning af fotos til tilgængelighed

### ISSUE THREAD

**Issue by hvingel-l** [OpenFKG/fkg-postgresql#118]
I billedtabellen oprettes et afkrydsningsfelt, som kan bruges ift. med upload af fotos til tilgængelighed.
Skal oprettes og fungere i stil med eksisterende "primær foto".

**Comment by cfischer00** [comment]
Skal ligge på fotoforbindelse (ligesom "primaer_kode"
