### ISSUE TITLE
Triggers hånterer ikke tomme tabeller

### ISSUE THREAD

**Issue by GregersP** [OpenFKG/fkg-postgresql#48]
Omend det er lidt mærkværdigt, ønsker man tomme tabeller (altså kun generelle atributter) på 7900 fotoforbindelse.

Triggers håndterer ikke dette særligt godt.

**Comment by cfischer00** [comment]
Ikke helt korrekt. Der er faktirsk andre attributter, jeg opdagede bare fejlen på et tidspunkt hvor jeg endnu ikke havde tilføjet nogle specifikke attributter 😄
