### ISSUE TITLE
Sæsonstart og -slut kolonner fejlagtigt ændret

### ISSUE THREAD

**Issue by geofyn** [OpenFKG/fkg-postgresql#70]
Ifm opdatering fra 2.6.3 til 3.0.0 fik kolonnerne saeson_st og saeson_sl ændret type fra dato til tekst. 

Dette var en fejl, fordi eksterne anvendere allerede var begyndt at bruge kolonnerne.

Dette skal derfor rettes tilbage for de 3 facilitetstemaer: t_5800_fac_pkt_t, t_5801_fac_fl_t, ~t_5802_fac_li_t~

**Comment by cfischer00** [comment]
Implementeres i 3.0.1

**Comment by cfischer00** [comment]
t_5802_fac_li_t har ikke sæson felter

**Comment by geofyn** [comment]
t_5802_fac_li_t skal gerne ligne t_5800_fac_pkt_t og t_5801_fac_fl_t her. Det vil sige have felterne:

saeson_k
saeson
saeson_st
saeson_sl
saeson_bem

Kræver det et nyt issue?

**Comment by cfischer00** [comment]
Ja tak - Nyt issue. Linjerne har aldrig haft saeson felter (jeg tror det er fordi de fleste ruter i naturen har åbent hele året
