### ISSUE TITLE
Yderligere link-felter til foldere

### ISSUE THREAD

**Issue by geofyn** [OpenFKG/fkg-postgresql#71]
Der er et behov for flere links til foldere for facilitetstemaerne.

For de 3 facilitetstemaer: t_5800_fac_pkt_t, t_5801_fac_fl_t, t_5802_fac_li_t skal følgende felter derfor tilføjes:
 - [x] foldelink1 (0-1024 tegn)
 - [x] foldelink2 (0-1024 tegn)
 - [x] foldelink3 (0-1024 tegn)

Således at der for de 3 facilitetstemaer er følgende felter:
folde_link (0-1024 tegn)
foldelink1 (0-1024 tegn)
foldelink2 (0-1024 tegn)
foldelink3 (0-1024 tegn)

**Comment by cfischer00** [comment]
Implementeres i 3.0.1
