### ISSUE TITLE
Opgradering til 3.0.1 fejler på saeson_sl og saeson_st hvor dag/måned er uden leading zero

### ISSUE THREAD

**Issue by mapcentia** [OpenFKG/fkg-postgresql#78]
Fx string `1/5`

`select ('1901' || '-' || substring('1/5' FROM 4 FOR 2) || '-' || substring('1/5' FROM 1 FOR 2))`

Resulterer i `1901--1/` som ikke kan castes til date.

Et fix kunne være at tilrette 2.6.3 til 3.0 således, at d/m string får et leading zero.

**Comment by GregersP** [comment]
Tak for indberetning. Som det ses, er der allerede en fix på vej 😊

**Comment by cfischer00** [comment]
Rettet i: upgrade_3_0_to_3_0_1.sql
