### ISSUE TITLE
primaer_kode_unique_idx omfatter tidligere versioner hvilket gør det umuligt at ændre primært foto 

### ISSUE THREAD

**Issue by mapcentia** [OpenFKG/fkg-postgresql#87]
UNIQUE INDEX primaer_kode_unique_idx:

https://github.com/OpenFKG/fkg-postgresql/blob/cad96bd8a363efa765af6f262ad385c0dca8692d/src/Upgrade_2_6_0_2A_to_2_6_3/Upgrade_2_6_0_2A_to_2_6_3.sql#L45-L51

Hvis man først har sat `primaer_kode=1` og ønsker at ændre den til en anden fotoforbindelse på samme objekt kan dette ikke lade sig gøre, da ovenstående UNIQUE constrain forhindrer det.

På en eller anden måde skal kun aktuelle fotoforbindelser tjekkes for dubletter.

**Comment by cfischer00** [comment]
Denne havde jeg overset. Jeg skal nok tage den med i næste version - indtil da, kan du køre:
```SQL
DROP INDEX fkg.primaer_kode_unique_idx;
```

Jeg skal nok sikre at det fremtidige script ikke fejler hvis du allerede har slettet indexet

**Comment by cfischer00** [comment]
Fixed with: https://github.com/OpenFKG/fkg-postgresql/commit/eba622e7b94a140e10de18d135a4ea826c43da18

Index droppet. Ny trigger constraint implementeret
