### ISSUE TITLE
Oprettelse af Parkeringsplads

### ISSUE THREAD

**Issue by geofyn** [OpenFKG/fkg-postgresql#93]
1291 er tidligere blevet ændret fra 1291 Parkeringsplads – til nu 1291 Holdeplads.
Vi vil gerne have oprettet facilitetstypen Parkeringsplads fx med koden 1351 på t_5800_fac_pkt og t_5801_fac_fl.
Gerne med denne beskrivelse "En parkeringsplads/et område er et officielt sted beregnet til at henstille køretøjer på, når de ikke bruges.".

**Comment by cfischer00** [comment]
Done with https://github.com/OpenFKG/fkg-postgresql/commit/8c9af2a067badbbc33c30275d33643e077a40f0b
